apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: fgmh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fgmh
    app.kubernetes.io/part-of: byoc-app-mgbl
  name: fgmh
spec:
  rules:
  - host: fgmh-byoc-ovip-tenant.apps.39bfe3bb33e557932278.hypershift.aws-2.ci.openshift.org
    http:
      paths:
      - backend:
          service:
            name: fgmh
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
