apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: fgmh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fgmh
    app.kubernetes.io/part-of: byoc-app-mgbl
  name: fgmh
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: fgmh
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: fgmh
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-ovip-tenant/byoc-app-mgbl/fgmh@sha256:c1f9fc9fd683134ecb13e50a711e1b157a5e4ea19a98f97de4f9818fe76fa2ed
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
